#!/usr/bin/env python3
"""Generate deterministic modem specification vectors.

Current-checkout wires are emitted as one-packet, stereo, 48 kHz PCM16 WAVs.
The historical V1/V2 entries are regenerated by extracting their exact source
files from the pinned commits with ``git show``; the current checkout's newer
transport modules are never substituted for them.

Run from the repository root:

    .venv/bin/python tools/spec_vectors.py

The output directory is scratch/spec-vectors unless --out is supplied.  The
files are intentionally untracked measurement artifacts; the printed manifest
contains the hashes copied into the transport specification.
"""
import argparse
import hashlib
import importlib.util
import json
import subprocess
import tempfile
import sys
import wave
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from animation_modem import transport3 as V3  # noqa: E402
from animation_modem.core import decode_packet  # noqa: E402
from animation_modem.engines import coder_for  # noqa: E402
from animation_modem.v6 import slot_symbols, tape_coder  # noqa: E402
from animation_modem.wavelet import _slot_carriers  # noqa: E402


SEED = 20260920
REFERENCE_RATE = V3.REFERENCE_RATE


def sha256(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def write_wav(path, audio):
    pcm = np.clip(np.rint(np.asarray(audio) * 32767), -32768, 32767)
    pcm = pcm.astype('<i2', copy=False)
    with wave.open(str(path), 'wb') as stream:
        stream.setnchannels(2)
        stream.setsampwidth(2)
        stream.setframerate(REFERENCE_RATE)
        stream.writeframes(pcm.tobytes())


def layout_record(layout, coder, profile, code):
    record = {
        'wire': layout.name,
        'profile': profile,
        'profile_code': code,
        'magic': layout.wire_magic.decode('ascii'),
        'top_bin': layout.top_bin,
        'band_hz': list(layout.band),
        'image_symbols': layout.image_symbols,
        'header_symbols': layout.header_symbols,
        'symbols': layout.symbols,
        'packet_samples': layout.packet,
        'frame_samples': layout.frame,
        'fps_48k': layout.fps,
        'capacity': layout.capacity,
        'coder_count': coder.count,
        'source_count': coder.source_count,
        'shapes': [list(shape) for shape in coder.shapes],
        'grids': [list(grid) for grid in coder.grids],
        'emission_ceiling_hz': layout.emission_ceiling or None,
    }
    return record


def placement_record(layout, coder):
    slots = coder.slots(layout)
    bins, channels = _slot_carriers(layout)
    symbols = slot_symbols(layout)
    home = slots[:coder.n_orig]
    copies = slots[coder.n_orig:]
    return {
        'original_count': int(coder.n_orig),
        'copy_count': int(len(coder.copy_of)),
        'unique_slots': int(len(np.unique(slots))),
        'copy_opposite_channel': bool(np.all(channels[home[coder.copy_of]]
                                              != channels[copies])),
        'copy_frequency_spread_bins_min': int(np.min(
            np.abs(bins[home[coder.copy_of]] - bins[copies])))
            if len(copies) else None,
        'copy_symbol_same_count': int(np.count_nonzero(
            symbols[home[coder.copy_of]] == symbols[copies]))
            if len(copies) else 0,
        'home_bin_range': [int(np.min(bins[home])), int(np.max(bins[home]))],
        'copy_bin_range': [int(np.min(bins[copies])), int(np.max(bins[copies]))]
            if len(copies) else None,
    }


def current_vector(out, name, layout, profile, code, seed, tolerance,
                   supplied_coder=None):
    coder = supplied_coder if supplied_coder is not None else coder_for(profile, layout)[0]
    rng = np.random.default_rng(seed)
    values = rng.uniform(-.7, .7, coder.source_count)
    audio = V3.encode(values, layout, coder, 1, 1, 1, profile=code)
    result = decode_packet(audio, layout, coder, coders={code: coder})
    reference = coder.inverse(coder.forward(values))
    measured = float(np.sqrt(np.mean((result.values-reference)**2))) \
        if result.values is not None else None
    path = out / f'{name}.wav'
    write_wav(path, audio)
    record = layout_record(layout, coder, profile, code)
    record.update({
        'version': name,
        'commit': '3b250ae3f6920dfe22eb716c2336a46e08a46004',
        'seed': seed,
        'file': path.name,
        'sha256': sha256(path),
        'decode_identity': result.identity,
        'measured_clean_rmse': measured,
        'expected_decode_tolerance': tolerance,
    })
    if hasattr(coder, 'copy_of'):
        record['placement'] = placement_record(layout, coder)
    return record


def _historical_module(commit, source_file, module_name, directory):
    root = Path(__file__).resolve().parent.parent
    source = subprocess.check_output(
        ['git', '-C', str(root), 'show', f'{commit}:{source_file}'])
    path = directory / f'{module_name}.py'
    path.write_bytes(source)
    spec = importlib.util.spec_from_file_location(module_name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def historical_v1_vector(out, seed):
    introduced = '364c29286a279680444cb7a1274db8de5101a79a'
    pinned = '99d60665688ef6af197be37ebcded57bc36aaf25'
    with tempfile.TemporaryDirectory(prefix='spec-v1-') as temp:
        v1 = _historical_module(pinned, 'animation_modem/transport.py',
                                'historical_v1', Path(temp))
        rng = np.random.default_rng(seed)
        image = Image.fromarray(np.uint8(rng.integers(
            0, 256, (96, 80, 3), dtype=np.uint8)))
        audio, prepared, _ = v1.encode(image, 1, 1, 1, profile='color')
        result = v1.decode_packet(audio)
        got = np.asarray(result.image.convert('RGB'), float)/255
        want = np.asarray(prepared.convert('RGB'), float)/255
        measured = float(np.sqrt(np.mean((got-want)**2))) \
            if result.image is not None else None
    path = out / 'v1.wav'
    write_wav(path, audio)
    return {
        'version': 'v1', 'introduced_commit': introduced,
        'pinned_commit': pinned, 'source_file': 'animation_modem/transport.py',
        'seed': seed, 'file': path.name, 'sha256': sha256(path),
        'decode_identity': result.identity,
        'measured_clean_rmse': measured,
        'expected_decode_tolerance': .11,
    }


def historical_v2_vector(out, seed):
    introduced = '33734bcf4308a8f9256eff4695905b745a18d356'
    pinned = '99d60665688ef6af197be37ebcded57bc36aaf25'
    with tempfile.TemporaryDirectory(prefix='spec-v2-') as temp:
        v2 = _historical_module(pinned, 'animation_modem/transport2.py',
                                'historical_v2', Path(temp))
        shapes = [(48, 40), (24, 20), (24, 20)]
        coder = v2.SourceCoder(shapes)
        values = np.random.default_rng(seed).uniform(-.7, .7, coder.count)
        layout = v2.PRESETS['wide']
        audio = v2.encode(values, layout, coder, 1, 1, 1)
        result = v2.decode_packet(audio, layout, coder)
        reference = coder.inverse(coder.forward(values))
        measured = float(np.sqrt(np.mean((result.values-reference)**2))) \
            if result.values is not None else None
    path = out / 'v2-99d60665.wav'
    write_wav(path, audio)
    return {
        'version': 'v2-99d60665', 'introduced_commit': introduced,
        'pinned_commit': pinned, 'source_file': 'animation_modem/transport2.py',
        'preset': 'wide', 'seed': seed, 'file': path.name,
        'sha256': sha256(path), 'decode_identity': result.identity,
        'measured_clean_rmse': measured,
        'expected_decode_tolerance': .001,
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=Path('scratch/spec-vectors'))
    parser.add_argument('--seed', type=int, default=SEED)
    args = parser.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)

    seed = int(args.seed)
    records = [historical_v1_vector(args.out, seed),
               historical_v2_vector(args.out, seed)]

    cases = [
        ('v3', V3.WIRE, 'color-dct', 0, .01),
        ('wire-hd', V3.WIRE_HD, 'hd-dwt', 2, .01),
        ('v5', V3.WIRE_HD, 'hd-dwt', 2, .01),
        ('wire-tape', V3.WIRE_TAPE, 'hd-dwt', 2, .07),
        ('wire-tape-25', V3.WIRE_TAPE_25, 'tape-80x60', 3, .08),
        ('v6', V3.WIRE_V6, 'v6-dct', 0, .55),
        ('v6-repeat', V3.WIRE_V6_REPEAT, 'v6-repeat-dct', 0, .60),
        ('v6-tape', V3.WIRE_V6, 'v6-tape-dct', 0, .55,
         tape_coder('dct')),
    ]
    for index, case in enumerate(cases):
        name, layout, profile, code, tolerance, *custom = case
        records.append(current_vector(out=args.out, name=name, layout=layout,
                                      profile=profile, code=code,
                                      seed=seed + index + 1,
                                      tolerance=tolerance,
                                      supplied_coder=custom[0] if custom else None))

    manifest = args.out / 'manifest.json'
    manifest.write_text(json.dumps(records, indent=2, sort_keys=True) + '\n')
    print(json.dumps(records, indent=2, sort_keys=True))
    print(f'Wrote {len(records)} vectors and {manifest}', file=sys.stderr)


if __name__ == '__main__':
    main()
